### ISSUE TITLE
[Queue task] Google cloud task handler response 302 request

### ISSUE THREAD

**Issue by mui-le** [a1comms/GaeFlexSupportL5#41]
Hi there, 
First, Thanks so much for this support.
I have made push queue task to the cloud successfully.
But when the queue handler response status 302 httpRequest, App error.
```
 httpRequest: {
  status:  302   
 }
```
I think it related this issue: https://cloud.google.com/tasks/docs/creating-appengine-handlers
But I don't know how to fix that.
Could you help me to check this issue? or example configuration about that?
Thanks!

**Comment by iamacarpet** [comment]
Hello @mui-le ,

Have you followed our documation at https://github.com/a1comms/GaeSupportLaravel/blob/php72-laravel55/docs/queue.md ?

HTTP 302 is a redirect and I checked the code, there are no conditions that are set to trigger a redirect, that I can see.

Is there any middleware or anything (login related) that could be redirecting?

Regards,
iamacarpet

**Comment by mui-le** [comment]
Hi @iamacarpet, Thanks for your check!
probably my YAML setting has made that. I'll check on my configuration again.
Thanks a lot!

**Comment by mui-le** [comment]
Update for laravel 5.8:
- remove prefix 'api' for tasks handler response gae
```php
App\Providers\RouteServiceProvider
/**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }

**Comment by iamacarpet** [comment]
Thanks @mui-le 

You may already be aware, but just let you know, this library only targets Laravel 5.5 at the moment.
