### ISSUE TITLE
us14 not found 

### ISSUE THREAD

**Issue by nibri10** [a1comms/GaeFlexSupportL5#58]
![image](https://user-images.githubusercontent.com/22533877/76800991-7b14f780-67b3-11ea-9794-11378fc2086f.png)

I tried to run on google cloud but it is not finding the **us-central1** region that is called **us14**

**Comment by nibri10** [comment]
@iamacarpet @flexgrip @fullkawa @matthewnessworthy

**Comment by matthewnessworthy** [comment]
@nibri10 can you log the value of `$zone` before the switch statement and report back the value please?

**Comment by iamacarpet** [comment]
@nibri10 you can also find the zone in the "resource" section of the access log entry in Stackdriver Logging, if it saves the need to deploy code to figure it out

**Comment by matthewnessworthy** [comment]
@nibri10 any updates?

**Comment by nibri10** [comment]
@matthewnessworthy pull request available

**Comment by nibri10** [comment]
And pull request by wagnerhitome add us6 zone in switch case @matthewnessworthy @iamacarpet @flexgrip @fullkawa
